// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article_content: dynamic(() => import("./ArticleContent")),
  hero: dynamic(() => import("./Hero")),
};
