// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  article_content: dynamic(() => import("./ArticleContent")),
  hero: dynamic(() => import("./Hero")),
  navbar: dynamic(() => import("./Navbar")),
};
